
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

export default function AboutPage() {
  return (
    <div className="p-4 md:p-8">
      <Card>
        <CardHeader>
          <CardTitle>About MediMind</CardTitle>
          <CardDescription>
            Your AI-Powered Health Companion
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <h3 className="text-lg font-semibold">Our Mission</h3>
            <p className="text-muted-foreground">
              MediMind is a prototype application designed to demonstrate the power of generative AI
              in the healthcare space. Our goal is to provide users with a tool for preliminary
              symptom analysis and to offer accessible, understandable health information. We aim
              to empower users to be more informed about their health, facilitating more
              productive conversations with healthcare professionals.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-semibold">How It Works</h3>
            <p className="text-muted-foreground">
              Using advanced large language models, MediMind analyzes the symptoms you provide,
              and can even interpret uploaded medical reports. It identifies potential conditions,
              explains its reasoning, and suggests appropriate next steps. The chatbot offers
              a conversational way to explore health topics in more detail.
            </p>
          </div>

          <Alert variant="destructive">
            <AlertTitle>Crucial Safety Information</AlertTitle>
            <AlertDescription>
              MediMind is an informational tool only and does not provide medical advice.
              The analysis is generated by an AI and may not be accurate or complete. It is
              not a substitute for a consultation with a qualified healthcare professional.
              Always consult a doctor or other qualified health provider with any questions you may have
              regarding a medical condition. Never disregard professional medical advice or delay in
              seeking it because of something you have read on this application.
            </AlertDescription>
          </Alert>

        </CardContent>
      </Card>
    </div>
  );
}
