
'use client';

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { FileText } from "lucide-react";

export function TermsOfServiceDialog() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <button className="flex items-center justify-center md:justify-start gap-2 text-muted-foreground hover:text-primary transition-colors">
            <FileText className="h-4 w-4"/>
            Terms of Service
        </button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle>Terms of Service for MediMind</DialogTitle>
          <DialogDescription>
            Last Updated: {new Date().toLocaleDateString()}
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-96 pr-6">
          <div className="space-y-4 text-sm text-muted-foreground">
            <h3 className="font-semibold text-foreground">1. Acceptance of Terms</h3>
            <p>
              By accessing or using the MediMind application ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, you may not access the Service. This Service is a prototype and is for informational purposes only.
            </p>

            <h3 className="font-semibold text-foreground">2. Description of Service</h3>
            <p>
              MediMind is an AI-powered prototype designed for preliminary symptom analysis and health information. It is not a substitute for professional medical advice, diagnosis, or treatment.
            </p>

            <h3 className="font-semibold text-foreground">3. User Accounts</h3>
            <p>
              When you create an account with us, you must provide information that is accurate, complete, and current at all times. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
            </p>

            <h3 className="font-semibold text-foreground">4. Disclaimers</h3>
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis. MediMind makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. The information provided is generated by an AI and may be inaccurate or incomplete.
            </p>

            <h3 className="font-semibold text-foreground">5. Limitation of Liability</h3>
            <p>
              In no event shall MediMind or its developers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on MediMind's application, even if MediMind or a MediMind authorized representative has been notified orally or in writing of the possibility of such damage.
            </p>

            <h3 className="font-semibold text-foreground">6. Governing Law</h3>
            <p>
              These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the user resides, without regard to its conflict of law provisions.
            </p>

            <h3 className="font-semibold text-foreground">7. Changes to Terms</h3>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
            </p>

            <h3 className="font-semibold text-foreground">8. Contact Us</h3>
            <p>
              If you have any questions about these Terms, please contact us at medimind84@gmail.com.
            </p>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
